#include "aesthetic_scorer.h"
#include <fstream>
#include <numeric>
#include <cmath>

AestheticScorer::AestheticScorer(const std::filesystem::path& appDataDir) {
    weights_path_ = appDataDir / "aesthetic_weights.bin";
    user_weights_.resize(512, 0.0f); // 512 dimensions for CLIP ViT-B/32
    loadWeights();
}

void AestheticScorer::loadWeights() {
    std::lock_guard<std::mutex> lock(weights_mtx_);
    if (!std::filesystem::exists(weights_path_)) return;

    std::ifstream in(weights_path_, std::ios::binary);
    if (in) {
        in.read(reinterpret_cast<char*>(user_weights_.data()), 512 * sizeof(float));
    }
}

void AestheticScorer::saveWeights() const {
    std::ofstream out(weights_path_, std::ios::binary);
    if (out) {
        out.write(reinterpret_cast<const char*>(user_weights_.data()), 512 * sizeof(float));
    }
}

void AestheticScorer::process(std::unique_ptr<ImageBuffer>& image, const ProcessingContext& ctx, ProcessingResult& result) {
    // 1. Get the CLIP vector generated by ClipEmbeddingProcessor
    auto it = result.sharedData.find("clip_vector");
    if (it == result.sharedData.end()) {
        result.warnings.push_back("No CLIP vector found. Aesthetic scoring skipped.");
        return;
    }

    const auto* featuresPtr = std::get_if<std::vector<float>>(&it->second);
    if (!featuresPtr || featuresPtr->size() != 512) {
        result.warnings.push_back("Invalid CLIP vector format.");
        return;
    }

    // 2. Compute Dot Product (Score = Vector * Weights)
    float score = 0.0f;
    {
        std::lock_guard<std::mutex> lock(weights_mtx_);
        for (size_t i = 0; i < 512; ++i) {
            score += (*featuresPtr)[i] * user_weights_[i];
        }
    }

    // 3. Save to metrics so GUI can sort by it
    result.metrics.push_back({"aesthetic_score", static_cast<double>(score)});
}

void AestheticScorer::train(const std::vector<float>& features, bool isGoodPhoto) {
    if (features.size() != 512) return;

    // Simple Hebbian Learning / Prototype update
    // Learning rate controls how fast the AI changes its mind
    const float learning_rate = 0.1f; 
    const float direction = isGoodPhoto ? 1.0f : -1.0f;

    std::lock_guard<std::mutex> lock(weights_mtx_);
    
    // Update weights
    float magnitude_sq = 0.0f;
    for (size_t i = 0; i < 512; ++i) {
        user_weights_[i] += learning_rate * direction * features[i];
        magnitude_sq += user_weights_[i] * user_weights_[i];
    }

    // Normalize weights to prevent values from exploding over time
    if (magnitude_sq > 0.0f) {
        float magnitude = std::sqrt(magnitude_sq);
        for (size_t i = 0; i < 512; ++i) {
            user_weights_[i] /= magnitude;
        }
    }

    saveWeights();
}